# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Main.hs
TARGET = QCLParser
MAIN = Main.hs
MAIN_IS = Quipper.Programs.QCLParser.Main
SUBDIR = src/Quipper/Programs/QCLParser
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Programs/QCLParser
BASEDIR = ../../../..
EXTRA_DIST = README bwt.qcl QCL-bwt-n4.out

include $(BASEDIR)/Makefile.common
