# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = BooleanFormula.hs Hex.hs HexBoard.hs Testing.hs Main.hs
TARGET = bf
MAIN = Main.hs
MAIN_IS = Quipper.Algorithms.BF.Main
SUBDIR = src/Quipper/Algorithms/BF
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Algorithms/BF
BASEDIR = ../../../..

include $(BASEDIR)/Makefile.common
