# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = GSE.hs Main.hs GSEData.hs JordanWigner.hs
TARGET = gse
MAIN = Main.hs
MAIN_IS = Quipper.Algorithms.GSE.Main
SUBDIR = src/Quipper/Algorithms/GSE
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Algorithms/GSE
BASEDIR = ../../../..
EXTRA_DIST = h_1e_ascii h_2e_ascii

include $(BASEDIR)/Makefile.common
