# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Definitions.hs QWTFP.hs Oracle.hs Alternatives.hs Simulate.hs Main.hs
TARGET = tf
MAIN = Main.hs
MAIN_IS = Quipper.Algorithms.TF.Main
SUBDIR = src/Quipper/Algorithms/TF
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Algorithms/TF
BASEDIR = ../../../..

include $(BASEDIR)/Makefile.common
