# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Main.hs Definitions.hs USV.hs Simulate.hs
TARGET = usv
MAIN = Main.hs
MAIN_IS = Quipper.Algorithms.USV.Main
SUBDIR = src/Quipper/Algorithms/USV
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Algorithms/USV
BASEDIR = ../../../..

include $(BASEDIR)/Makefile.common
