# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MULTIPLE_MAINS = yes
NODOC = yes
TARGET = Test1 Test2
MODULES = Test1.hs Test2.hs Test1Import.hs Test2Import.hs
SUBPACKAGE = template-tests
SUBDIR = src/Quipper/Demos/Template
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Demos/Template
BASEDIR = ../../../..

include $(BASEDIR)/Makefile.common
