# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Main.hs CircLiftingImport.hs \
 TemplateOracle.hs QDouble.hs	\
 RealFunc.hs QLS.hs QSignedIntAux.hs \
 QSignedInt.hs Utils.hs

TARGET = qls
MAIN = Main.hs
MAIN_IS = Quipper.Algorithms.QLS.Main
SUBDIR = src/Quipper/Algorithms/QLS
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Algorithms/QLS
BASEDIR = ../../../..



include $(BASEDIR)/Makefile.common
