# This file is part of Quipper. Copyright (C) 2011-2019. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = BWT.hs Simulate.hs Alternative.hs Template.hs Definitions.hs Main.hs
TARGET = bwt
MAIN = Main.hs
MAIN_IS = Quipper.Algorithms.BWT.Main
SUBDIR = src/Quipper/Algorithms/BWT
SUBDIR_ROOT = src
SUBDIR_REL = Quipper/Algorithms/BWT
BASEDIR = ../../../..

include $(BASEDIR)/Makefile.common
